name: Run Artisan Command

on:
  workflow_dispatch: # Memungkinkan menjalankan workflow manual dari GitHub
  push:              # Atau otomatis saat ada push ke branch tertentu
    branches:
      - main
    schedule:          # Menjadwalkan workflow berjalan otomatis
      - cron: '0 0 * * *' # Menjadwalkan setiap hari pada pukul 00:00 UTC

jobs:
  artisan-command:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kode repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Pastikan sesuai dengan versi PHP aplikasi Anda
        extensions: mbstring, pdo, bcmath, intl
        tools: composer

    # 3. Install dependencies dengan Composer
    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    # 4. Setup file .env
    - name: Setup .env file
      run: |
        cp .env.example .env
        sed -i "s|DB_CONNECTION=.*|DB_CONNECTION=pgsql|g" .env
        sed -i "s|DB_HOST=.*|DB_HOST=${{ secrets.SUPABASE_DB_HOST }}|g" .env
        sed -i "s|DB_PORT=.*|DB_PORT=${{ secrets.SUPABASE_DB_PORT }}|g" .env
        sed -i "s|DB_DATABASE=.*|DB_DATABASE=${{ secrets.SUPABASE_DB_NAME }}|g" .env
        sed -i "s|DB_USERNAME=.*|DB_USERNAME=${{ secrets.SUPABASE_DB_USERNAME }}|g" .env
        sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }}|g" .env

    # 5. Generate application key
    - name: Generate application key
      run: php artisan key:generate

    # 7. Jalankan command artisan
    - name: Run Artisan Command
      run: php artisan run:nodescript
